version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/ -v || exit 1
      
  build:
    commands:
      - echo "Build started on `date`"
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - 'tests/**'